services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - sql
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=Reactivities;User Id=sa;Password=Password@1;TrustServerCertificate=true

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: 'Password@1'
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    platform: "linux/amd64"
volumes:
  sql-data: